// ═════ PURPOSE ═════

/* 
The purpose of this script is to automate the process of populating the parameter AAI_LevelElevationSort which is used to provide a numerical value for sorting elements from linked models based on the elevation value of the level where they are hosted.

The parameter AAI_LevelElevationSort is a shared parameter to be applied to the following categories:

- Areas
- Doors
- Rooms
- Specialty Equipment (smoke and fire curtains, shutters, garage doors, ...)

*/

// ═══ AREAS (GROSS INTERNAL AREA) ═══

// Set up variables for counting elements later

int missingParamAreasNIA = 0;
int readOnlyAreasNIA = 0;
int changedAreasNIA = 0;
int populatedAreasNIA = 0;

// set up transaction

using (Transaction tAreasNIA = new Transaction (doc, "Set NIA Areas elevation parameter"))
{
	tAreasNIA.Start();
	
	try
	{
		// two-step filtered element collector	
		// ⯌ generated by ChatGPT Revit Add-in Code Provider on 2026-06-03
		
		AreaScheme NIAScheme = new FilteredElementCollector(doc) // step 1 retrieves the area scheme named "NIA"
			.OfClass(typeof(AreaScheme))
			.Cast<AreaScheme>()
			.FirstOrDefault(x => x.Name == "NIA");
			
		if (NIAScheme == null)
		{
			TaskDialog.Show(
			"DEBUG",
			$"NIA Area Scheme not found.");
			return;
		}
		
		List <Area> NIAAreas = new FilteredElementCollector(doc) // step 2 retrieves all areas within area scheme "NIA"
			.OfClass(typeof(SpatialElement))
			.WhereElementIsNotElementType()
			.OfType<Area>()
			.Where(a => a.AreaScheme != null &&
			 			a.AreaScheme.Id == NIAScheme.Id)
			.ToList();
			
		TaskDialog.Show(
		"DEBUG",
		$"NIA Areas Found: {NIAAreas.Count}");
		
		// the outputs of the filtered element collector are grouped by level
		
		var groupedNIAAreas = NIAAreas.GroupBy(a => a.LevelId);
		
		// the NIA areas are then processed within each group
		
		foreach (var group in groupedNIAAreas)
		{
			Level NIAAreaLevel = doc.GetElement(group.Key) as Level;
			
			if (NIAAreaLevel == null)
				continue;
				
			// returns the elevation in mm
			double areasNIALevelElevationMetric = Math.Round((NIAAreaLevel.Elevation)*304.8);
			
			// this second variable is used to avoid processing/modifying areas that already have the correct value
			string areasNIATargetValue = areasNIALevelElevationMetric.ToString();
			
			foreach (Area NIAArea in group)
			{
				Parameter NIAAreaP = NIAArea.LookupParameter("AAI_LevelElevation");
				
				if (NIAAreaP == null)
				{
					missingParamAreasNIA++;
					continue;
				}
				else if (NIAAreaP.IsReadOnly)
				{
					readOnlyAreasNIA++;
					continue;
				}
				else if (string.Equals(NIAAreaP.AsString(),areasNIATargetValue))
				{
					populatedAreasNIA++;
					continue;
				}
				else
				{
					NIAAreaP.Set(areasNIATargetValue);
					changedAreasNIA++;
				}
			}
		}
	}
	
	catch (Exception ex)
	{
	    TaskDialog.Show("ERROR", ex.ToString());
	}
		
	
	tAreasNIA.Commit();
}

TaskDialog.Show(
	"NIA Area Scheme Areas Elevation Update Summary",
	$"Missing Parameter: {missingParamAreasNIA}\n" +
	$"Read Only: {readOnlyAreasNIA}\n" +
	$"Already Populated: {populatedAreasNIA}\n" +
	$"Changed: {changedAreasNIA}");
