// ═════ PURPOSE ═════

/* 
The purpose of this script is to automate the process of populating the parameter AAI_LevelElevationSort which is used to provide a numerical value for sorting elements from linked models based on the elevation value of the level where they are hosted.

The parameter AAI_LevelElevationSort is a shared parameter to be applied to the following categories:

- Areas
- Doors
- Rooms
- Specialty Equipment (smoke and fire curtains, shutters, garage doors, ...)

*/

// ═══ AREAS ═══

// Set up variables for counting elements later

int missingParamAreasGEA = 0;
int readOnlyAreasGEA = 0;
int changedAreasGEA = 0;
int populatedAreasGEA = 0;

// set up transaction

using (Transaction tAreasGEA = new Transaction (doc, "Set GEA Areas elevation parameter"))
{
	tAreasGEA.Start();
	
	// two-step filtered element collector	
	// ⯌ generated by ChatGPT Revit Add-in Code Provider on 2026-06-03
	
	AreaScheme GEAScheme = new FilteredElementCollector(doc) // step 1 retrieves the area scheme named "GEA"
		.OfClass(typeof(AreaScheme))
		.Cast<AreaScheme>()
		.First(x => x.Name == "GEA");
	
	List <Area> GEAAreas = new FilteredElementCollector(doc) // step 2 retrieves all areas within area scheme "GEA"
		.OfClass(typeof(Area))
		.WhereElementIsNotElementType()
		.Cast<Area>()
		.Where(a => a.AreaScheme.Id == GEAScheme.Id)
		.ToList();
		
	TaskDialog.Show(
	"DEBUG",
	$"GEA Areas Found: {geaAreas.Count}");
	
	// the outputs of the filtered element collector are grouped by level
	
	var groupedGEAAreas = GEAAreas.GroupBy(a => a.LevelId);
	
	// the GEA areas are then processed within each group
	
	foreach (var group in groupedGEAAreas)
	{
		Level GEAAreaLevel = doc.GetElement(group.Key) as Level;
		
		if (GEAAreaLevel == null)
			continue;
			
		// returns the elevation in mm
		double areasGEALevelElevationMetric = Math.Round((GEAAreaLevel.Elevation)*304.8);
		
		// this second variable is used to avoid processing/modifying areas that already have the correct value
		string areasGEATargetValue = areasGEALevelElevationMetric.ToString();
		
		foreach (Area GEAArea in group)
		{
			Parameter GEAAreaP = GEAArea.LookupParameter("AAI_LevelElevation");
			
			if (GEAAreaP == null)
			{
				missingParamAreasGEA++;
				continue;
			}
			else if (GEAAreaP.IsReadOnly)
			{
				readOnlyAreasGEA++;
				continue;
			}
			else if (string.Equals(GEAAreaP.AsString(),areasGEATargetValue)
			{
				populatedAreasGEA++;
				continue;
			}
			else
			{
				GEAAreaP.Set(areasGEATargetValue);
				changedAreasGEA++;
			}
		}
	}
	
	tAreasGEA.Commit();
}

TaskDialog.Show(
	"GEA Area Scheme Areas Elevation Update Summary",
	$"Missing Parameter: {missingParamAreasGEA}\n" +
	$"Read Only: {readOnlyAreasGEA}\n" +
	$"Already Populated: {populatedAreasGEA}\n" +
	$"Changed: {changedAreasGEA}");
