// ═════ PURPOSE ═════

/* 
The purpose of this script is to automate the process of populating the parameter AAI_LevelElevationSort which is used to provide a numerical value for sorting elements from linked models based on the elevation value of the level where they are hosted.

The parameter AAI_LevelElevationSort is a shared parameter to be applied to the following categories:

- Areas
- Doors
- Rooms
- Specialty Equipment (smoke and fire curtains, shutters, garage doors, ...)

*/

// ═══ AREAS (GROSS INTERNAL AREA) ═══

// Set up variables for counting elements later

int missingParamAreasGIA = 0;
int readOnlyAreasGIA = 0;
int changedAreasGIA = 0;
int populatedAreasGIA = 0;

// set up transaction

using (Transaction tAreasGIA = new Transaction (doc, "Set GIA Areas elevation parameter"))
{
	tAreasGIA.Start();
	
	try
	{
		// two-step filtered element collector	
		// ⯌ generated by ChatGPT Revit Add-in Code Provider on 2026-06-03
		
		AreaScheme GIAScheme = new FilteredElementCollector(doc) // step 1 retrieves the area scheme named "GIA"
			.OfClass(typeof(AreaScheme))
			.Cast<AreaScheme>()
			.FirstOrDefault(x => x.Name == "GIA");
			
		if (GIAScheme == null)
		{
			TaskDialog.Show(
			"DEBUG",
			$"GIA Area Scheme not found.");
			return;
		}
		
		List <Area> GIAAreas = new FilteredElementCollector(doc) // step 2 retrieves all areas within area scheme "GIA"
			.OfClass(typeof(SpatialElement))
			.WhereElementIsNotElementType()
			.OfType<Area>()
			.Where(a => a.AreaScheme != null &&
			 			a.AreaScheme.Id == GIAScheme.Id)
			.ToList();
			
		TaskDialog.Show(
		"DEBUG",
		$"GIA Areas Found: {GIAAreas.Count}");
		
		// the outputs of the filtered element collector are grouped by level
		
		var groupedGIAAreas = GIAAreas.GroupBy(a => a.LevelId);
		
		// the GIA areas are then processed within each group
		
		foreach (var group in groupedGIAAreas)
		{
			Level GIAAreaLevel = doc.GetElement(group.Key) as Level;
			
			if (GIAAreaLevel == null)
				continue;
				
			// returns the elevation in mm
			double areasGIALevelElevationMetric = Math.Round((GIAAreaLevel.Elevation)*304.8);
			
			// this second variable is used to avoid processing/modifying areas that already have the correct value
			string areasGIATargetValue = areasGIALevelElevationMetric.ToString();
			
			foreach (Area GIAArea in group)
			{
				Parameter GIAAreaP = GIAArea.LookupParameter("AAI_LevelElevation");
				
				if (GIAAreaP == null)
				{
					missingParamAreasGIA++;
					continue;
				}
				else if (GIAAreaP.IsReadOnly)
				{
					readOnlyAreasGIA++;
					continue;
				}
				else if (string.Equals(GIAAreaP.AsString(),areasGIATargetValue))
				{
					populatedAreasGIA++;
					continue;
				}
				else
				{
					GIAAreaP.Set(areasGIATargetValue);
					changedAreasGIA++;
				}
			}
		}
	}
	
	catch (Exception ex)
	{
	    TaskDialog.Show("ERROR", ex.ToString());
	}
		
	
	tAreasGIA.Commit();
}

TaskDialog.Show(
	"GIA Area Scheme Areas Elevation Update Summary",
	$"Missing Parameter: {missingParamAreasGIA}\n" +
	$"Read Only: {readOnlyAreasGIA}\n" +
	$"Already Populated: {populatedAreasGIA}\n" +
	$"Changed: {changedAreasGIA}");
