int missingParamRooms = 0;
int readOnlyRooms = 0;
int changedRooms = 0;
int populatedRooms = 0;

// set up transaction

using (Transaction tRooms = new Transaction (doc, "Set room parameter"))
{
	tRooms.Start();
	
	try
	{
		// filtered element collector
		// ⯌ generated by ChatGPT Revit Add-in Code Provider on 2026-06-03
				
		List <Room> rooms = new FilteredElementCollector(doc)
			.OfCategory(BuiltInCategory.OST_Rooms)
			.WhereElementIsNotElementType()
			.OfType<Room>()
			.ToList();
			
		TaskDialog.Show(
		"DEBUG",
		$"Rooms Found: {rooms.Count}");
		
		// the outputs of the filtered element collector are grouped by level
		
		var groupedRooms = rooms.GroupBy(a => a.LevelId);
		
		// the NIA areas are then processed within each group
		
		foreach (var group in groupedRooms)
		{
			Level groupLevel = doc.GetElement(group.Key) as Level;
			
			if (groupLevel == null)
				continue;
				
			// returns the elevation in mm
			double RoomsLevelElevationMetric = Math.Round((groupLevel.Elevation)*304.8);
			
			// this second variable is used to avoid processing/modifying areas that already have the correct value
			string RoomsTargetValue = RoomsLevelElevationMetric.ToString();
			
			foreach (Room r in group)
			{
				Parameter roomP = r.LookupParameter("AAI_LevelElevation");
				
				if (roomP == null)
				{
					missingParamRooms++;
					continue;
				}
				else if (roomP.IsReadOnly)
				{
					readOnlyRooms++;
					continue;
				}
				else if (string.Equals(roomP.AsString(),RoomsTargetValue))
				{
					populatedRooms++;
					continue;
				}
				else
				{
					roomP.Set(RoomsTargetValue);
					changedRooms++;
				}
			}
		}
	}
	
	catch (Exception ex)
	{
	    TaskDialog.Show("ERROR", ex.ToString());
	}
		
	
	tRooms.Commit();
}

TaskDialog.Show(
	"Rooms Elevation Update Summary",
	$"Missing Parameter: {missingParamRooms}\n" +
	$"Read Only: {readOnlyRooms}\n" +
	$"Already Populated: {populatedRooms}\n" +
	$"Changed: {changedRooms}");
